### ISSUE TITLE
missing node and rust installers

### ISSUE THREAD

**Issue by easternbloc** [keithamus/dotfiles#2]

**Comment by keithamus** [comment]
Yeah I am currently working on those. Feel free to send a PR :smile:.

For Rust, use https://github.com/brson/multirust
For npm, use https://github.com/creationix/nvm

**Comment by easternbloc** [comment]
I'm kinda mid way through updating so it's kinda :boom: right now if I make any headway I'll raise one!

**Comment by keithamus** [comment]
Oh wait... nvm one already exists!

**Comment by keithamus** [comment]
bc14ae5 fixes Node, and comments out rust for now.

**Comment by easternbloc** [comment]
:love_letter:

**Comment by keithamus** [comment]
a37ffc4 adds rust.

**Comment by keithamus** [comment]
@easternbloc can you try out 365f196? It ditches mjolnir and replaces it with HAMMERSPOON. :hammer: :fork_and_knife: (why is there no emoji for spoon?!).

**Comment by easternbloc** [comment]
Love the comment on this: https://discussions.apple.com/thread/6895483?start=0&tstart=0 also a middle finger emoji haha

**Comment by keithamus** [comment]
[middle finger emoji exists now!](http://emojipedia.org/reversed-hand-with-middle-finger-extended/).

**Comment by easternbloc** [comment]
works like a :peach: :ok_hand:
