### ISSUE TITLE
Perhaps use fisherman?

### ISSUE THREAD

**Issue by easternbloc** [keithamus/dotfiles#3]
https://github.com/github/dmca/blob/master/2016-02-04-Wahoo-2.md

Maybe migrate to fisherman?

**Comment by easternbloc** [comment]
https://github.com/fisherman/fisherman

**Comment by keithamus** [comment]
Well that sucks. PRs are welcome :smile:

**Comment by easternbloc** [comment]
I'll try and get round to it. I just spotted it yesterday and thought the same thing. Fisherman claims to be better so that's probably the way to go...

**Comment by easternbloc** [comment]
![](https://media1.giphy.com/media/sz3pnTuOYyupa/200.gif#0)
